/*
 *
 * Automatically generated file; DO NOT EDIT.
 * U-Boot 2016.01 Configuration
 *
 */
#define CONFIG_CMD_BOOTM 1
#define CONFIG_IPQ807x_I2C 1
#define CONFIG_PCI_IPQ 1
#define CONFIG_USB 1
#define CONFIG_OF_SEPARATE 1
#define CONFIG_SYS_GENERIC_BOARD 1
#define CONFIG_OF_TRANSLATE 1
#define CONFIG_BOOTSTAGE_STASH_ADDR 0x0
#define CONFIG_HAVE_PRIVATE_LIBGCC 1
#define CONFIG_CMD_BDI 1
#define CONFIG_ARM 1
#define CONFIG_CREATE_ARCH_SYMLINK 1
#define CONFIG_DM_SEQ_ALIAS 1
#define CONFIG_SYS_VENDOR "qca"
#define CONFIG_QCA8033_PHY 1
#define CONFIG_QCA8081_PHY 1
#define CONFIG_CMD_SAVEENV 1
#define CONFIG_CMD_MISC 1
#define CONFIG_SYS_CPU "armv7"
#define CONFIG_BOOTSTAGE_USER_COUNT 0x20
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_DM_SERIAL 1
#define CONFIG_CMD_FLASH 1
#define CONFIG_USB_XHCI_IPQ 1
#define CONFIG_DM_DEVICE_REMOVE 1
#define CONFIG_HAVE_GENERIC_BOARD 1
#define CONFIG_REQUIRE_SERIAL_CONSOLE 1
#define CONFIG_SYS_EXTRA_OPTIONS ""
#define CONFIG_SIMPLE_BUS 1
#define CONFIG_CMD_CRC32 1
#define CONFIG_SYS_BOARD "hw29765589p0p512p1024p4x4p8x8"
#define CONFIG_SYS_CONFIG_NAME "hw29765589p0p512p1024p4x4p8x8"
#define CONFIG_NET 1
#define CONFIG_QCA_AQUANTIA_PHY 1
#define CONFIG_DM_WARN 1
#define CONFIG_PARTITION_UUIDS 1
#define CONFIG_CMD_GO 1
#define CONFIG_SYS_MALLOC_CLEAR_ON_INIT 1
#define CONFIG_NETGEAR_PUSH_BUTTON 1
#define CONFIG_SYS_HZ 1000
#define CONFIG_CPU_V7 1
#define CONFIG_SUPPORT_OF_CONTROL 1
#define CONFIG_TARGET_HW29765589P0P512P1024P4X4P8X8 1
#define CONFIG_DM_STDIO 1
#define CONFIG_LOCALVERSION ""
#define CONFIG_CMD_LOADB 1
#define CONFIG_SYS_PROMPT "IPQ807x# "
#define CONFIG_CMD_MEMORY 1
#define CONFIG_CMD_ECHO 1
#define CONFIG_LOCALVERSION_AUTO 1
#define CONFIG_SYS_ARCH "arm"
#define CONFIG_CMD_DM 1
#define CONFIG_HAS_VBAR 1
#define CONFIG_EXPERT 1
#define CONFIG_SYS_SOC "qca_hw29765589p0p512p1024p4x4p8x8"
#define CONFIG_CMD_ITEST 1
#define CONFIG_DM_USB 1
#define CONFIG_BOOTSTAGE_STASH_SIZE 0x4096
#define CONFIG_OF_CONTROL 1
#define CONFIG_CMD_LOADS 1
#define CONFIG_QCA_COMMON 1
#define CONFIG_CMD_NET 1
#define CONFIG_DEFAULT_DEVICE_TREE ""
#define CONFIG_NET_TFTP_VARS 1
#define CONFIG_FIT 1
#define CONFIG_DM 1
#define CONFIG_HAS_THUMB2 1
#define CONFIG_SYS_MALLOC_F 1
#define CONFIG_FIT_VERBOSE 1
#define CONFIG_SYS_MALLOC_F_LEN 0x400
#define CONFIG_QCA8075_PHY 1
#define CONFIG_CMD_SOURCE 1
